### ISSUE TITLE
Add Expenses screen

### ISSUE THREAD

**Issue by therealharpaljadeja** [celo-org/ethglobal-london#3]
```[tasklist]
### Tasks
- [x] Show total effective balance
- [x] Add "Add Expense" button
- [x] Show a list of Expenses
```
