### ISSUE TITLE
Add Expenses Smart Contract

### ISSUE THREAD

**Issue by therealharpaljadeja** [celo-org/ethglobal-london#6]
```[tasklist]
### Tasks
- [x] Add User Object (Expenses[], Contributions[])
- [x] `createExpense` method
- [x] `getExpense` method
- [x] `getUserStats` method
- [x] `getSettlement` method
- [x] `settle` method
- [x] Add deploy script
- [x] Verify contract on Celoscan
```

Global arrays for Expenses and Contributions

```solidity
struct User {
  int256 effectiveBalance;
  uint256[] expenses;
  uint256[] settlements;
}
```
